=== joseadt/mh-wilds-builder/public/schemas/armor-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "ArmorSkill": {
            "properties": {
                "level": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ArmorType": {
            "enum": [
                "HEAD",
                "CHEST",
                "ARMS",
                "WAIST",
                "LEGS"
            ],
            "type": "string"
        },
        "DecorationSlot": {
            "properties": {
                "level": {
                    "$ref": "#/definitions/SlotLevel"
                }
            },
            "type": "object"
        },
        "SlotLevel": {
            "enum": [
                1,
                2,
                3,
                4
            ],
            "type": "number"
        },
        "Stats": {
            "properties": {
                "affinity": {
                    "type": "number"
                },
                "attack": {
                    "type": "number"
                },
                "critBoost": {
                    "type": "number"
                },
                "defense": {
                    "type": "number"
                },
                "dragonResist": {
                    "type": "number"
                },
                "fireResist": {
                    "type": "number"
                },
                "iceResist": {
                    "type": "number"
                },
                "thunderResist": {
                    "type": "number"
                },
                "waterResist": {
                    "type": "number"
                }
            },
            "type": "object"
        }
    },
    "properties": {
        "id": {
            "type": "number"
        },
        "name": {
            "type": "string"
        },
        "set": {
            "type": "string"
        },
        "skills": {
            "items": {
                "$ref": "#/definitions/ArmorSkill"
            },
            "type": "array"
        },
        "slots": {
            "items": {
                "$ref": "#/definitions/DecorationSlot"
            },
            "type": "array"
        },
        "stats": {
            "$ref": "#/definitions/Stats"
        },
        "type": {
            "$ref": "#/definitions/ArmorType"
        }
    },
    "type": "object"
}

=== joseadt/mh-wilds-builder/public/test-data/armor.json
[
    {
        "id": 1,
        "name": "Rathalos Helm",
        "set": "Rathalos",
        "type": "HEAD",
        "stats": {
            "defense": 50,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": 3,
            "waterResist": -2,
            "thunderResist": 0,
            "iceResist": -1,
            "dragonResist": 1
        },
        "skills": [
            {
                "name": "Attack Boost",
                "level": 1
            }
        ],
        "slots": [{ "level": 1 }]
    },
    {
        "id": 2,
        "name": "Kushala Glare",
        "set": "Kushala",
        "type": "HEAD",
        "stats": {
            "defense": 52,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": -3,
            "waterResist": 2,
            "thunderResist": -2,
            "iceResist": 4,
            "dragonResist": 1
        },
        "skills": [
            {
                "name": "Ice Resistance",
                "level": 2
            }
        ],
        "slots": [{ "level": 1 }, { "level": 2 }]
    },
    {
        "id": 3,
        "name": "Diablos Helm",
        "set": "Diablos",
        "type": "HEAD",
        "stats": {
            "defense": 53,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": 2,
            "waterResist": 0,
            "thunderResist": -3,
            "iceResist": -1,
            "dragonResist": 1
        },
        "skills": [
            {
                "name": "Defense Boost",
                "level": 2
            }
        ]
    },
    {
        "id": 4,
        "name": "Nargacuga Mail",
        "set": "Nargacuga",
        "type": "CHEST",
        "stats": {
            "defense": 48,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": -3,
            "waterResist": 1,
            "thunderResist": -2,
            "iceResist": 0,
            "dragonResist": 1
        },
        "skills": [
            {
                "name": "Critical Boost",
                "level": 1
            }
        ],
        "slots": [{ "level": 1 }, { "level": 2 }]
    },
    {
        "id": 5,
        "name": "Lagiacrus Mail",
        "set": "Lagiacrus",
        "type": "CHEST",
        "stats": {
            "defense": 50,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": -4,
            "waterResist": 4,
            "thunderResist": -2,
            "iceResist": 0,
            "dragonResist": 1
        },
        "skills": [
            {
                "name": "Water Resistance",
                "level": 2
            }
        ],
        "slots": [{ "level": 1 }, { "level": 2 }]
    },
    {
        "id": 6,
        "name": "Teostra Mail",
        "set": "Teostra",
        "type": "CHEST",
        "stats": {
            "defense": 55,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": 4,
            "waterResist": -2,
            "thunderResist": -1,
            "iceResist": 2,
            "dragonResist": 3
        },
        "skills": [
            {
                "name": "Fire Resistance",
                "level": 3
            }
        ],
        "slots": [{ "level": 2 }, { "level": 4 }]
    },
    {
        "id": 7,
        "name": "Anjanath Vambraces",
        "set": "Anjanath",
        "type": "ARMS",
        "stats": {
            "defense": 52,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": 2,
            "waterResist": -3,
            "thunderResist": 0,
            "iceResist": -2,
            "dragonResist": 1
        },
        "skills": [
            {
                "name": "Attack Boost",
                "level": 1
            }
        ],
        "slots": [{ "level": 3 }]
    },
    {
        "id": 8,
        "name": "Barioth Vambraces",
        "set": "Barioth",
        "type": "ARMS",
        "stats": {
            "defense": 49,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": -3,
            "waterResist": 0,
            "thunderResist": -1,
            "iceResist": 3,
            "dragonResist": 1
        },
        "skills": [
            {
                "name": "Ice Resistance",
                "level": 2
            }
        ],
        "slots": [{ "level": 4 }]
    },
    {
        "id": 9,
        "name": "Lunastra Coil",
        "set": "Lunastra",
        "type": "WAIST",
        "stats": {
            "defense": 55,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": 4,
            "waterResist": -2,
            "thunderResist": -1,
            "iceResist": 3,
            "dragonResist": 2
        },
        "skills": [
            {
                "name": "Fire Resistance",
                "level": 2
            }
        ],
        "slots": [{ "level": 1 }]
    },
    {
        "id": 10,
        "name": "Uragaan Coil",
        "set": "Uragaan",
        "type": "WAIST",
        "stats": {
            "defense": 60,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": 3,
            "waterResist": -2,
            "thunderResist": -2,
            "iceResist": 2,
            "dragonResist": 0
        },
        "skills": [
            {
                "name": "Defense Boost",
                "level": 2
            }
        ],
        "slots": [{ "level": 1 }, { "level": 3 }, { "level": 4 }]
    },
    {
        "id": 11,
        "name": "Bazelgeuse Greaves",
        "set": "Bazelgeuse",
        "type": "LEGS",
        "stats": {
            "defense": 57,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": 3,
            "waterResist": 0,
            "thunderResist": -3,
            "iceResist": 1,
            "dragonResist": 2
        },
        "skills": [
            {
                "name": "Defense Boost",
                "level": 2
            }
        ],
        "slots": [{ "level": 2 }, { "level": 3 }]
    },
    {
        "id": 12,
        "name": "Kirin Leg Guards",
        "set": "Kirin",
        "type": "LEGS",
        "stats": {
            "defense": 45,
            "attack": 0,
            "affinity": 0,
            "critBoost": 0,
            "fireResist": -3,
            "waterResist": 2,
            "thunderResist": 4,
            "iceResist": -1,
            "dragonResist": 0
        },
        "skills": [
            {
                "name": "Thunder Resistance",
                "level": 3
            }
        ],
        "slots": [{ "level": 1 }, { "level": 1 }]
    }
]
